"""Added a column to the Lottery table for file url

Revision ID: a51e969d2e71
Revises: 3992b6e64d18
Create Date: 2018-11-08 00:34:08.426812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51e969d2e71'
down_revision = '3992b6e64d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotteries', 'url')
    # ### end Alembic commands ###
