"""Init

Revision ID: b69834d07b20
Revises: 
Create Date: 2018-11-07 23:52:01.404084

"""
from alembic import op
import sqlalchemy as sa
from app import MagicJSON

# revision identifiers, used by Alembic.
revision = 'b69834d07b20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('details', MagicJSON, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('lotteries')
    # ### end Alembic commands ###
